# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn test
    - run: yarn build
      env:
        REACT_APP_MAP_API_KEY: ${{ secrets.MAP_API_KEY }}
    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'push' && matrix.node-version == '22.x' }}
      with:
        name: deployment
        path: build/*
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: deployment
        path: ./build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        cname: wedding.berviantoleo.my.id
